# Comparative Sentiment Analyses 
## prototyping shiny plots

### Libraries

```{r}
library(dplyr)
library(ggplot2)
library(wordcloud2)
```


### Load data

```{r}

# dave chapelle, full and vader

dc_full <- read.csv('dcfull.csv')
dc_vd_titl <- read.csv('dcvader.titles.csv')
dc_vd_post <- read.csv('dcvader.posts.csv')
dc_vd_comm <- read.csv('dcvader.comments.csv')



# joe manchin, full and vader

jm_full <- read.csv('jmfull.csv')
jm_vd_titl <- read.csv('jmvader.titles.csv')
jm_vd_post <- read.csv('jmvader.posts.csv')
jm_vd_comm <- read.csv('jmvader.comments.csv')

```


### Reduce to needed values only

```{r}
# full 
dc_full <- dc_full %>% select (subreddit, thread.date, title, post, thread.score, thread.number.comments, comment.date, comment, comment.score, comment_id)


jm_full <- jm_full %>% select (subreddit, thread.date, title, post, thread.score, thread.number.comments, comment.date, comment, comment.score, comment_id)


# vader 
dc_titl <- dc_vd_titl %>% select(text,pos,neg)
dc_post <- dc_vd_post %>% select(text,pos,neg)
dc_comm <- dc_vd_comm %>% select(text,pos,neg)

jm_titl <- jm_vd_titl %>% select(text,pos,neg)
jm_post <- jm_vd_post %>% select(text,pos,neg)
jm_comm <- jm_vd_comm %>% select(text,pos,neg)

```

# write reduced files into csvs
```{r}

write.csv(dc_full, "dc_full.csv", row.names = F)
write.csv(dc_titl, "dc_titl.csv", row.names = F)
write.csv(dc_post, "dc_post.csv", row.names = F)
write.csv(dc_comm, "dc_comm.csv", row.names = F)

write.csv(dc_full, "dc_full.csv", row.names = F)
write.csv(dc_titl, "dc_titl.csv", row.names = F)
write.csv(dc_post, "dc_post.csv", row.names = F)
write.csv(dc_comm, "dc_comm.csv", row.names = F)

write.csv(jm_full, "jm_full.csv", row.names = F)
write.csv(jm_titl, "jm_titl.csv", row.names = F)
write.csv(jm_post, "jm_post.csv", row.names = F)
write.csv(jm_comm, "jm_comm.csv", row.names = F)

write.csv(jm_full, "jm_full.csv", row.names = F)
write.csv(jm_titl, "jm_titl.csv", row.names = F)
write.csv(jm_post, "jm_post.csv", row.names = F)
write.csv(jm_comm, "jm_comm.csv", row.names = F)


```


### Tab Two - Overview Comparisons by Text

```{r}
# options: text (all, title, post, comment), sentiment (pos, neg)
# for 'all' text option, create summary of vd means 




# density

ggplot() + 
  geom_density(aes(x=jm_vd_titl$pos))
  geom_density(aes(x=cd_vd_titl$pos))
    
# time series

ggplot() +   
  
  
  
# scatter with size for score 
  
ggplot() + 


```


### Tab Three - Text Collection by Sentiment

```{r}





```


### Tab Four - Subreddit Stats

```{r}

# group by subreddit for vd scores 



```


### Tab Five - Wordcloud

```{r}

# combined, contoversy, biggest subreddits 





```

