## Data collection

### Libraries: RedditExtractoR --- these files extracted on Nov 4th, 2021

```{r}
library(RedditExtractoR)

```

### Extract data for Dave Chapelle

```{r}

dc_urls <- find_thread_urls(keywords="dave chapelle netflix trans", sort_by = 'relevance', period = 'month')

dc_subreddits <- unique(dc_urls$subreddit)

dc_comments <- get_thread_content(dc_urls$url)

write.csv(dc_comments[["threads"]], "dcthreads.csv", row.names = FALSE)
write.csv(dc_comments[["comments"]], "dccomments.csv", row.names = FALSE)
write.csv(dc_subreddits, "dcsubreddits.csv", row.names = FALSE)
```

### Extract data for Joe Manchin

```{r}

jm_urls <- find_thread_urls(keywords="joe manchin climate bill", sort_by = 'relevance', period = 'month')

jm_subreddits <- unique(jm_urls$subreddit)

jm_comments <- get_thread_content(jm_urls$url)

write.csv(jm_comments[["threads"]], "jmthreads.csv", row.names = FALSE)
write.csv(jm_comments[["comments"]], "jmcomments.csv", row.names = FALSE)
write.csv(jm_subreddits, "jmsubreddits.csv", row.names = FALSE)
```


