---
output: html_document
editor_options: 
  chunk_output_type: inline
---
# Sentiment Analyses EDA

### Libraries:

```{r echo=FALSE}
library(sentimentr)
library(vader)
library(lubridate)
library(ggplot2)
library(scales)
library(reshape2)
library(dplyr)
library(tidyverse)
library(stringr)

# rm(list=ls())

```

## Dave Chapelle

```{r}
# import DFs
dc_comm <- read.csv("Dave Chapelle Comments.csv")
dc_thre <- read.csv("Dave Chapelle Threads.csv")


# merge into one DF
dc_thre <- dc_thre %>% dplyr::select(subreddit, url, thread.author=author, 
                                     thread.date=date, thread.title=title, 
                                     thread.text=text, 
                                     thread.score=score, 
                                     thread.number.comments=comments)

dc_comm <- dc_comm %>% dplyr::select(url, comment.author=author, 
                                     comment.date=date, comment, 
                                     comment.score=score, comment_id)


dc_full <- merge(dc_thre, dc_comm)

```


# sentimentr 

```{r}

# threads

dc_sr_thre <- get_sentences(dc_thre$thread.text)
dc_sr_thre <- sentiment_by(dc_sr_thre, dc_thre$thread.text)
plot(dc_sr_thre$word_count, dc_sr_thre$ave_sentiment)

df <- merge(dc_sr_thre, dc_thre)
cor(df$thread.score, df$thread.number.comments)
cor(df$thread.score, df$ave_sentiment)

r


# comments

dc_sr_comm <- get_sentences(dc_full$comment)
dc_sr_comm <- sentiment_by(dc_sr_comm, dc_full$comment)

mean(dc_sr_comm$sentiment)

```


# Valence Aware Dictionary and sEntiment Reasoner (VADER)

```{r}
# dc_vcsents <- vader_df(dc_comm$comment)
# dc_vtsents <- vader_df(dc_thre$text)
# write.csv(dc_vcsents,"DC vader comment sents.csv", row.names = F)
# write.csv(dc_vtsents, "DC vader thread sents.csv", row.names = F)

dc_vcsents <- read.csv('DC vader comment sents.csv')
dc_vtsents <- read.csv('DC vader thread sents.csv')

dc_sents <- rename(dc_sents,comment = text)

head(dc_sents)
dc_uv <- merge(dcfull,dc_sentsM)
head(dc_uv)
write.csv(dc_uv, "Vader Comment Data Merge.csv", row.names = F)

View(dc_uv)

cor(dc_uv)


```


```{r}
dsent <- dc_sents[,c(3:6)]

plot(dsent$pos, dsent$neg)
# drops <- c("word_scores","but_count")
# dc_sents1 <- dc_sents[ , !(names(dc_sents) %in% drops)]
```
```{r}
# measuring for average length of comment

play <- dc_sents$text

play3 <- sapply(play, str_count)
head(play3)

play2 <- strsplit(play, " ")

wl <- sapply(play2, length)

mean(wl)
summary(wl)

plot(density(wl))

library(MASS)
```


## sentimentr

```{r}


```


```{r}
dsent1 <- pivot_longer(dsent, c(1:4), 
                       names_to = "type", 
                       values_to = "valence", 
                       values_drop_na = TRUE)

dmeans <- dsent1 %>% 
  group_by(type) %>% 
  summarise(avg_valence = mean(valence))

dtype <- dsent1 %>% group_by(type)

barplot(dmeans$avg_valence)
boxplot(dtype$valence ~ dtype$type)

dtype

```

### upvote analysis

```{r}



```


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

## Joe Manchin analysis

```{r}


jmfull <- read.csv("Joe Manchin Comments.csv")
jmfull$comment[1:5]
jm_sents <- vader_df(jmfull$comment)
View(jm_sents)
write.csv(jm_sents,"JM vader sents.csv", row.names = F)
jm_sents <- read.csv('JM vader sents.csv')

str(jm_sents)

jsent <- jm_sents[,c(3:6)]


# drops <- c("word_scores","but_count")
# dc_sents1 <- dc_sents[ , !(names(dc_sents) %in% drops)]



jsent1 <- pivot_longer(jsent, c(1:4), names_to = "type", values_to = "valence", values_drop_na = TRUE)

jmeans <- jsent1 %>% 
  group_by(type) %>% 
  summarise(avg_valence = mean(valence))

?barplot

barplot(jmeans$avg_valence)
jsent_type <- jsent1 %>% group_by(type)

boxplot(jsent_type, xlab='measure', ylab='valence', ann=T)


```

