---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Joe Manchin Controversy Sentiment Analyses (EDA)

### Libraries:

```{r results=FALSE, message=FALSE, warning=FALSE}
library(sentimentr)
library(vader)
library(lubridate)
library(ggplot2)
library(scales)
library(reshape2)
library(dplyr)
library(tidyverse)
library(stringr)

# rm(list=ls())

```

### Load and merge dataframes

```{r}
# import DFs
jm_comm <- read.csv("jmcomments.csv")
jm_thre <- read.csv("jmthreads.csv")


# merge into one DF
jm_thre <- jm_thre %>% dplyr::select(subreddit, url, thread.author=author, 
                                     thread.date=date, title, 
                                     post=text, 
                                     thread.score=score, 
                                     thread.number.comments=comments)

jm_comm <- jm_comm %>% dplyr::select(url, comment.author=author, 
                                     comment.date=date, comment, 
                                     comment.score=score, comment_id)


jm_full <- merge(jm_thre, jm_comm)

```



### Valence Aware Dictionary and sEntiment Reasoner (VADER)

```{r}
# get sentiments 

jm_vd_titl <- vader_df(jm_full$title)
jm_vd_post <- vader_df(jm_full$post)
jm_vd_comm <- vader_df(jm_comm$comment)

write.csv(jm_vd_titl, "jmvader.titles.csv", row.names = F)
write.csv(jm_vd_post,"jmvader.posts.csv", row.names = F)
write.csv(jm_vd_comm,"jmvader.comments.csv", row.names = F)


jm_vd_titl <- read.csv('jmvader.titles.csv')
jm_vd_post <- read.csv('jmvader.posts.csv')
jm_vd_comm <- read.csv('jmvader.comments.csv')


sum(is.na(jm_vd_titl$neu))


jm_vd_titl %>%anti_join(stop_words, by = "title")


```


## pos/neg across texts - density

```{r}
ggplot(data = jm_vd_comm, aes(x=pos, fill='yellow',alpha=.5))+
  geom_density() +
  # Change the fill colour to differentiate it
  geom_density(data=jm_vd_post, fill="purple", alpha = .3) +
  geom_density(data=drop_na(jm_vd_titl), fill="green", alpha = .3) +
  labs(title = "Distribution of positivity") +
  labs(y="Density")+
  labs(x="positive response")

p1
```


## pos/neg across texts across time - line

```{r}

jm_date <- jm_thre %>% select(date=thread.date,title,post)
jm_vd_title_s <- jm_vd_titl %>% select (title=text, pos, neg)
jm_vd_post_s <- jm_vd_post %>% select(post=text,pos,neg)
jm_vd_date <- merge(jm_date, distinct(jm_vd_title_s))
jm_vd_datepost <- merge(jm_date, distinct(jm_vd_post_s))
jm_vd_date$date <- ymd(jm_vd_date$date)
jm_vd_datepost$date <- ymd(jm_vd_datepost$date)

p <- ggplot(data = jm_vd_date, aes(x=date, y=pos)) +
  geom_line( color="#69b3a2") + 
  xlab("date") +
  scale_x_date(labels=date_format ("%b %y")) +
  theme(axis.text.x=element_text(angle=60, hjust=1)) 
p

sum(is.na(distinct(jm_vd_post)))
j <- distinct(jm_vd_post)


p <- ggplot(data = jm_vd_date, aes(x=date, y=pos, fill="purple")) +
  geom_line() + 
  geom_line(data = jm_vd_datepost, color="#69b3a2") +
  xlab("date") +
  scale_x_date(labels=date_format ("%b %y")) +
  theme(axis.text.x=element_text(angle=60, hjust=1)) 
p

```



### sentimentr 

```{r results=c(1,6)}
# 1. threads

# 1.1 by thread text
jm_sr_thre <- get_sentences(jm_thre$thread.text)
jm_sr_thre <- sentiment_by(jm_sr_thre, jm_thre$thread.text)

# summary
summary(jm_sr_thre)

# correlations
df1 <- merge(jm_sr_thre, jm_thre)
cor(df1$thread.score, df1$thread.number.comments) # 0.853
cor(df1$ave_sentiment, df1$word_count) ## 0.345* <--- marginally high r^2
cor(df1$ave_sentiment, df1$thread.score) # -0.035
cor(df1$ave_sentiment, df1$thread.number.comments) # -0.042


# 1.2 by thread title
jm_sr_titl <- get_sentences(jm_thre$thread.title)
jm_sr_titl <- sentiment_by(jm_sr_titl, jm_thre$thread.title)

# summary
summary(jm_sr_titl)

# correlations 
df12 <- merge(jm_sr_titl, jm_thre)
cor(df12$ave_sentiment, df12$word_count)  ## 0.424* <--- marginally high r^2 
cor(df12$ave_sentiment, df12$thread.score)  # 0.051
cor(df12$ave_sentiment, df12$thread.number.comments) # 0.02

# 1.3 comments

# by comment
jm_sr_comm <- get_sentences(jm_full$comment)
jm_sr_comm <- sentiment_by(jm_sr_comm, jm_full$comment)


df13 <-merge(jm_sr_comm, jm_full)
cor(df13$ave_sentiment, df13$word_count) # 0.03
cor(df13$ave_sentiment, df13$comment.score) # -0.003
cor(df13$ave_sentiment, df13$thread.number.comments) # 0.015
cor(df13$ave_sentiment, df13$thread.score) # 0.009


# summary
summary(jm_sr_comm)

# plots
plot(density(jm_sr_titl$ave_sentiment), 
     xlim=c(-1.5,1.5),
     ylim=c(0,7),
     main = "JM Average Sentiment by Text", 
     xlab = "Average sentimentr Score")
lines(density(jm_sr_thre$ave_sentiment),
      col = 2)
lines(density(jm_sr_comm$ave_sentiment),
      col = 3)
legend("topleft", 
       c('title text','post text','comments'),
       col = 1:3,
       lty = 1,
       title = "Text Colors")

```


```{r}
## 2. arranging by groups

# 2.1 by subreddit
# text
jm_sr_thre_sub <- get_sentences(jm_thre$thread.text)
jm_sr_thre_sub <- sentiment_by(jm_sr_thre_sub, jm_thre$subreddit)

df13 <- merge(jm_sr_thre_sub, jm_thre)

df13 %>%
  group_by(subreddit) %>%
  mutate(subreddit = fct_reorder(subreddit, ave_sentiment)) %>%
  ggplot(aes(x=subreddit, y=ave_sentiment)) +
  geom_bar(stat='identity')


# title
jm_sr_titl_sub <- get_sentences(jm_thre$thread.title)
jm_sr_titl_sub <- sentiment_by(jm_sr_titl_sub, jm_thre$subreddit)

df14 <- merge(jm_sr_titl, jm_thre)



# 2.2 by author


```


```{r}
# 3. Trends over time


```

